-- JavaScript Daily Tasks Questions

-- BEGINNER (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('JavaScript', 'beginner', 'Write a function that takes two numbers and returns their sum.', 'Use the + operator to add numbers', 10),
('JavaScript', 'beginner', 'Create a variable that stores your name and log it to the console.', 'Use let or const to declare variables', 10),
('JavaScript', 'beginner', 'Write a function that checks if a number is even or odd.', 'Use the modulo operator % to check divisibility', 10),
('JavaScript', 'beginner', 'Create an array of 5 fruits and log the first and last element.', 'Arrays are zero-indexed, use [0] and [length-1]', 10),
('JavaScript', 'beginner', 'Write a for loop that prints numbers from 1 to 10.', 'Use for(let i=1; i<=10; i++)', 10),
('JavaScript', 'beginner', 'Create an object representing a person with name, age, and city properties.', 'Use curly braces {} to create objects', 10),
('JavaScript', 'beginner', 'Write a function that converts Celsius to Fahrenheit.', 'Formula: F = (C × 9/5) + 32', 10),
('JavaScript', 'beginner', 'Use an if-else statement to check if a person is an adult (age >= 18).', 'Compare the age variable with 18', 10),
('JavaScript', 'beginner', 'Create a function that returns the length of a string.', 'Use the .length property of strings', 10),
('JavaScript', 'beginner', 'Write code to concatenate two strings with a space between them.', 'Use + operator or template literals', 10);

-- INTERMEDIATE (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('JavaScript', 'intermediate', 'Write a function that removes duplicates from an array.', 'Use Set or filter with indexOf', 20),
('JavaScript', 'intermediate', 'Create a function that reverses a string without using built-in reverse.', 'Use a loop or split, reverse, join', 20),
('JavaScript', 'intermediate', 'Implement a function that finds the maximum value in an array.', 'Use Math.max with spread or reduce', 20),
('JavaScript', 'intermediate', 'Write a function that counts the occurrences of each character in a string.', 'Use an object to store counts', 20),
('JavaScript', 'intermediate', 'Create a function that flattens a nested array one level deep.', 'Use concat with spread or flat(1)', 20),
('JavaScript', 'intermediate', 'Implement a debounce function that delays function execution.', 'Use setTimeout and clearTimeout', 20),
('JavaScript', 'intermediate', 'Write a function that checks if a string is a palindrome.', 'Compare string with its reverse', 20),
('JavaScript', 'intermediate', 'Create a function that groups array elements by a property.', 'Use reduce to build grouped object', 20),
('JavaScript', 'intermediate', 'Implement a function that deep clones an object.', 'Use JSON.parse(JSON.stringify()) or recursion', 20),
('JavaScript', 'intermediate', 'Write a function that sorts an array of objects by a specific key.', 'Use sort() with a compare function', 20);

-- ADVANCED (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('JavaScript', 'advanced', 'Implement a Promise.all from scratch.', 'Track resolved promises count and reject on first error', 30),
('JavaScript', 'advanced', 'Create a memoization function for expensive computations.', 'Use a cache object with function arguments as key', 30),
('JavaScript', 'advanced', 'Implement a simple event emitter with on, off, and emit methods.', 'Use an object to store event listeners', 30),
('JavaScript', 'advanced', 'Write a function that performs deep comparison of two objects.', 'Recursively compare all nested properties', 30),
('JavaScript', 'advanced', 'Implement a throttle function that limits function calls.', 'Track last execution time', 30),
('JavaScript', 'advanced', 'Create a function that curries any function with any number of arguments.', 'Return functions until all arguments collected', 30),
('JavaScript', 'advanced', 'Implement a simple Observable pattern.', 'Create subscribe, unsubscribe, and notify methods', 30),
('JavaScript', 'advanced', 'Write an async function that retries failed API calls with exponential backoff.', 'Double wait time after each failure', 30),
('JavaScript', 'advanced', 'Implement a Least Recently Used (LRU) cache.', 'Use Map to maintain insertion order', 30),
('JavaScript', 'advanced', 'Create a function that implements the pipe/compose pattern.', 'Chain functions using reduce', 30);
-- Python Daily Tasks Questions

-- BEGINNER (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Python', 'beginner', 'Print "Hello, World!" to the console.', 'Use print() function', 10),
('Python', 'beginner', 'Create a variable and print its type.', 'Use type() function', 10),
('Python', 'beginner', 'Write a function that adds two numbers.', 'Use def function_name(a, b): return a + b', 10),
('Python', 'beginner', 'Create a list and print its length.', 'Use len() function', 10),
('Python', 'beginner', 'Write a for loop that prints numbers 1 to 10.', 'Use range(1, 11)', 10),
('Python', 'beginner', 'Create a dictionary with name and age keys.', 'Use {key: value} syntax', 10),
('Python', 'beginner', 'Write an if-else to check if a number is even.', 'Use modulo operator %', 10),
('Python', 'beginner', 'Take user input and print it.', 'Use input() function', 10),
('Python', 'beginner', 'Create a string and convert it to uppercase.', 'Use .upper() method', 10),
('Python', 'beginner', 'Write a function with a default parameter.', 'Use def func(param=default):', 10);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Python', 'beginner', 'Write a Python program that prints Hello World.', 'Use print()', 10),
('Python', 'beginner', 'Declare a variable and assign an integer value.', 'No type declaration needed', 10),
('Python', 'beginner', 'Take user input from the console.', 'Use input()', 10),
('Python', 'beginner', 'Convert user input to an integer.', 'Use int()', 10),
('Python', 'beginner', 'Add two numbers provided by the user.', 'Use arithmetic operators', 10),
('Python', 'beginner', 'Check whether a number is even or odd.', 'Use modulo operator', 10),
('Python', 'beginner', 'Write a program using if-else conditions.', 'Use if keyword', 10),
('Python', 'beginner', 'Create a list of numbers.', 'Use square brackets', 10),
('Python', 'beginner', 'Access elements of a list.', 'Use index positions', 10),
('Python', 'beginner', 'Find the length of a list.', 'Use len()', 10),
('Python', 'beginner', 'Iterate through a list using a for loop.', 'Use for loop', 10),
('Python', 'beginner', 'Create a tuple and access its elements.', 'Tuples are immutable', 10),
('Python', 'beginner', 'Create a dictionary with key-value pairs.', 'Use curly braces', 10),
('Python', 'beginner', 'Access values from a dictionary.', 'Use keys', 10),
('Python', 'beginner', 'Write a function that returns a value.', 'Use def and return', 10),
('Python', 'beginner', 'Call a function with arguments.', 'Pass parameters', 10),
('Python', 'beginner', 'Create a string and print it.', 'Use quotes', 10),
('Python', 'beginner', 'Find the length of a string.', 'Use len()', 10),
('Python', 'beginner', 'Concatenate two strings.', 'Use + operator', 10),
('Python', 'beginner', 'Use a while loop to print numbers.', 'Use while keyword', 10);

-- INTERMEDIATE (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Python', 'intermediate', 'Use list comprehension to create squares of numbers.', '[x**2 for x in range(10)]', 20),
('Python', 'intermediate', 'Write a function using *args and **kwargs.', 'Args is tuple, kwargs is dictionary', 20),
('Python', 'intermediate', 'Create a class with constructor and methods.', 'Use __init__ for constructor', 20),
('Python', 'intermediate', 'Read and write to a JSON file.', 'Use json.load() and json.dump()', 20),
('Python', 'intermediate', 'Implement error handling with try-except.', 'Catch specific exceptions', 20),
('Python', 'intermediate', 'Use lambda functions with map and filter.', 'lambda x: expression', 20),
('Python', 'intermediate', 'Create a decorator function.', 'Function that wraps another function', 20),
('Python', 'intermediate', 'Work with regular expressions using re module.', 'Use re.match(), re.search(), re.findall()', 20),
('Python', 'intermediate', 'Create a generator function using yield.', 'Yield pauses and returns value', 20),
('Python', 'intermediate', 'Use context managers with the with statement.', 'with open() as f:', 20);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Python', 'intermediate', 'Write a function that removes duplicates from a list.', 'Use set()', 20),
('Python', 'intermediate', 'Reverse a list without using built-in reverse.', 'Use slicing or loop', 20),
('Python', 'intermediate', 'Count frequency of elements in a list.', 'Use dictionary', 20),
('Python', 'intermediate', 'Check if a string is a palindrome.', 'Compare string with reverse', 20),
('Python', 'intermediate', 'Use list comprehension to create a new list.', 'Use concise syntax', 20),
('Python', 'intermediate', 'Sort a list of numbers.', 'Use sorted()', 20),
('Python', 'intermediate', 'Handle exceptions using try-except.', 'Catch errors', 20),
('Python', 'intermediate', 'Read data from a file.', 'Use open() with read', 20),
('Python', 'intermediate', 'Write data to a file.', 'Use write() method', 20),
('Python', 'intermediate', 'Use lambda function.', 'Anonymous function', 20),
('Python', 'intermediate', 'Filter a list using filter().', 'Use lambda', 20),
('Python', 'intermediate', 'Map a function to a list.', 'Use map()', 20),
('Python', 'intermediate', 'Use enumerate in a loop.', 'Get index and value', 20),
('Python', 'intermediate', 'Use zip to combine lists.', 'Pair elements', 20),
('Python', 'intermediate', 'Create a class with attributes.', 'Use class keyword', 20),
('Python', 'intermediate', 'Create an object from a class.', 'Instantiate class', 20),
('Python', 'intermediate', 'Implement inheritance.', 'Use parent class', 20),
('Python', 'intermediate', 'Override a method in subclass.', 'Use same method name', 20),
('Python', 'intermediate', 'Use __init__ constructor.', 'Initialize attributes', 20),
('Python', 'intermediate', 'Use modules and import statements.', 'Use import keyword', 20);

-- ADVANCED (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Python', 'advanced', 'Implement a class with magic methods (__str__, __repr__).', 'Magic methods customize behavior', 30),
('Python', 'advanced', 'Create an async function using asyncio.', 'Use async def and await', 30),
('Python', 'advanced', 'Implement a metaclass for class creation.', 'Class of a class, use type()', 30),
('Python', 'advanced', 'Create a thread-safe singleton pattern.', 'Use threading.Lock for safety', 30),
('Python', 'advanced', 'Implement a custom context manager class.', 'Define __enter__ and __exit__', 30),
('Python', 'advanced', 'Write a coroutine for concurrent tasks.', 'Use asyncio.gather() for concurrency', 30),
('Python', 'advanced', 'Create a property with getter and setter.', 'Use @property and @name.setter', 30),
('Python', 'advanced', 'Implement memoization using functools.', 'Use @functools.lru_cache', 30),
('Python', 'advanced', 'Create a dataclass with validation.', 'Use @dataclass and __post_init__', 30),
('Python', 'advanced', 'Implement the observer pattern.', 'Subjects notify observers of changes', 30);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Python', 'advanced', 'Implement a decorator function.', 'Use wrapper function', 30),
('Python', 'advanced', 'Create a generator using yield.', 'Use yield keyword', 30),
('Python', 'advanced', 'Implement context manager using with.', 'Use __enter__ and __exit__', 30),
('Python', 'advanced', 'Use multithreading in Python.', 'Use threading module', 30),
('Python', 'advanced', 'Use multiprocessing for CPU-bound tasks.', 'Use multiprocessing module', 30),
('Python', 'advanced', 'Implement memoization using decorators.', 'Use cache dictionary', 30),
('Python', 'advanced', 'Build a REST API using Flask.', 'Define routes', 30),
('Python', 'advanced', 'Build a REST API using FastAPI.', 'Use async endpoints', 30),
('Python', 'advanced', 'Handle asynchronous code using asyncio.', 'Use async and await', 30),
('Python', 'advanced', 'Parse JSON data in Python.', 'Use json module', 30),
('Python', 'advanced', 'Serialize objects using pickle.', 'Use pickle module', 30),
('Python', 'advanced', 'Implement a singleton design pattern.', 'Use class-level instance', 30),
('Python', 'advanced', 'Optimize code using profiling.', 'Use cProfile', 30),
('Python', 'advanced', 'Work with regular expressions.', 'Use re module', 30),
('Python', 'advanced', 'Implement unit tests using unittest.', 'Use unittest framework', 30),
('Python', 'advanced', 'Use pytest for testing.', 'Write test functions', 30),
('Python', 'advanced', 'Connect to a database using Python.', 'Use DB-API', 30),
('Python', 'advanced', 'Implement ORM using SQLAlchemy.', 'Define models', 30),
('Python', 'advanced', 'Build a web scraper.', 'Use requests and BeautifulSoup', 30),
('Python', 'advanced', 'Deploy a Python application.', 'Use WSGI server', 30);
-- React Daily Tasks Questions

-- BEGINNER (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('React', 'beginner', 'Create a functional component that displays "Hello World".', 'Use function ComponentName() { return <div>...</div> }', 10),
('React', 'beginner', 'Pass a prop to a child component and display it.', 'Define props in function parameter, access with props.name', 10),
('React', 'beginner', 'Create a component with a click handler that shows an alert.', 'Use onClick={handleClick} in JSX', 10),
('React', 'beginner', 'Use useState to create a counter with increment button.', 'const [count, setCount] = useState(0)', 10),
('React', 'beginner', 'Render a list of items using map().', 'Use array.map() inside JSX with key prop', 10),
('React', 'beginner', 'Create a component that conditionally renders content.', 'Use ternary operator or && in JSX', 10),
('React', 'beginner', 'Style a component using inline styles.', 'Use style={{ property: value }}', 10),
('React', 'beginner', 'Create an input field that updates state on change.', 'Use onChange with e.target.value', 10),
('React', 'beginner', 'Import and use an external CSS file.', 'Use import "./styles.css"', 10),
('React', 'beginner', 'Create a component that receives and renders children.', 'Use props.children to render nested content', 10);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('React', 'beginner', 'Create a basic React functional component.', 'Use function or arrow function', 10),
('React', 'beginner', 'Render a React component to the DOM.', 'Use ReactDOM.createRoot', 10),
('React', 'beginner', 'Use JSX to display text.', 'Return JSX from component', 10),
('React', 'beginner', 'Create a component that accepts props.', 'Use props parameter', 10),
('React', 'beginner', 'Display props inside JSX.', 'Use curly braces', 10),
('React', 'beginner', 'Create a component with state using useState.', 'Import useState hook', 10),
('React', 'beginner', 'Update state on button click.', 'Use setter function', 10),
('React', 'beginner', 'Handle a click event in React.', 'Use onClick handler', 10),
('React', 'beginner', 'Render a list using map().', 'Use key attribute', 10),
('React', 'beginner', 'Add conditional rendering using if statement.', 'Use conditions inside component', 10),
('React', 'beginner', 'Add conditional rendering using ternary operator.', 'Use condition ? A : B', 10),
('React', 'beginner', 'Create a controlled input field.', 'Bind value and onChange', 10),
('React', 'beginner', 'Create a form with submit handler.', 'Use onSubmit', 10),
('React', 'beginner', 'Prevent default form submission.', 'Use event.preventDefault()', 10),
('React', 'beginner', 'Use React Fragment to wrap elements.', 'Use <> </>', 10),
('React', 'beginner', 'Pass a function as a prop.', 'Use callback props', 10),
('React', 'beginner', 'Add inline styles to a component.', 'Use style object', 10),
('React', 'beginner', 'Add class names conditionally.', 'Use template literals', 10),
('React', 'beginner', 'Use default props in a component.', 'Set default values', 10),
('React', 'beginner', 'Create a reusable button component.', 'Use props for customization', 10);

-- INTERMEDIATE (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('React', 'intermediate', 'Use useEffect to fetch data on component mount.', 'Pass empty dependency array [] for mount only', 20),
('React', 'intermediate', 'Create a controlled form with multiple inputs.', 'Store form state in single object with useState', 20),
('React', 'intermediate', 'Implement a custom hook for form handling.', 'Extract form logic into useForm hook', 20),
('React', 'intermediate', 'Use React.memo to prevent unnecessary re-renders.', 'Wrap component in React.memo()', 20),
('React', 'intermediate', 'Create a context for theme management.', 'Use createContext, Provider, and useContext', 20),
('React', 'intermediate', 'Implement error boundaries for graceful error handling.', 'Use componentDidCatch or react-error-boundary', 20),
('React', 'intermediate', 'Use useCallback to memoize a function.', 'Wrap function in useCallback with dependencies', 20),
('React', 'intermediate', 'Create a reusable modal component.', 'Use portal and manage open/close state', 20),
('React', 'intermediate', 'Implement lazy loading for a component.', 'Use React.lazy() with Suspense', 20),
('React', 'intermediate', 'Use useReducer for complex state management.', 'Define reducer function with switch cases', 20);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('React', 'intermediate', 'Use useEffect to run code on component mount.', 'Use empty dependency array', 20),
('React', 'intermediate', 'Fetch data from an API using useEffect.', 'Use fetch or axios', 20),
('React', 'intermediate', 'Handle loading and error states.', 'Use multiple states', 20),
('React', 'intermediate', 'Create a custom hook.', 'Extract reusable logic', 20),
('React', 'intermediate', 'Use useRef to access DOM elements.', 'Use ref attribute', 20),
('React', 'intermediate', 'Optimize rendering using React.memo.', 'Prevent unnecessary re-renders', 20),
('React', 'intermediate', 'Lift state up between components.', 'Move state to parent', 20),
('React', 'intermediate', 'Use context API for global state.', 'Create Context Provider', 20),
('React', 'intermediate', 'Implement controlled vs uncontrolled components.', 'Compare input handling', 20),
('React', 'intermediate', 'Create a dynamic form with multiple inputs.', 'Use object state', 20),
('React', 'intermediate', 'Implement conditional rendering based on API data.', 'Check data availability', 20),
('React', 'intermediate', 'Use useCallback to memoize functions.', 'Wrap function with hook', 20),
('React', 'intermediate', 'Use useMemo to optimize calculations.', 'Memoize computed values', 20),
('React', 'intermediate', 'Handle component cleanup in useEffect.', 'Return cleanup function', 20),
('React', 'intermediate', 'Implement pagination for a list.', 'Slice array or API params', 20),
('React', 'intermediate', 'Implement search filtering in a list.', 'Use filter method', 20),
('React', 'intermediate', 'Create a modal component.', 'Use conditional rendering', 20),
('React', 'intermediate', 'Implement error boundaries.', 'Use class component', 20),
('React', 'intermediate', 'Lazy load a component.', 'Use React.lazy', 20),
('React', 'intermediate', 'Use Suspense for loading fallback.', 'Wrap lazy component', 20);

-- ADVANCED (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('React', 'advanced', 'Implement infinite scroll with useEffect and IntersectionObserver.', 'Observe last element for loading more', 30),
('React', 'advanced', 'Create a compound component pattern for a tabs system.', 'Use React.Children and cloneElement', 30),
('React', 'advanced', 'Implement optimistic updates with rollback on error.', 'Update UI immediately, revert if API fails', 30),
('React', 'advanced', 'Build a render props pattern for data fetching.', 'Pass render function as child or prop', 30),
('React', 'advanced', 'Create a higher-order component for authentication.', 'Wrap component and check auth status', 30),
('React', 'advanced', 'Implement virtualization for a large list.', 'Use react-window or react-virtual', 30),
('React', 'advanced', 'Create a custom hook for WebSocket connections.', 'Manage connection lifecycle in useEffect', 30),
('React', 'advanced', 'Implement undo/redo functionality using useReducer.', 'Maintain history stack of states', 30),
('React', 'advanced', 'Build a drag and drop interface without libraries.', 'Use HTML5 drag events with React', 30),
('React', 'advanced', 'Create a suspense-compatible data fetching solution.', 'Throw promise for pending state', 30);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('React', 'advanced', 'Implement a virtualized list.', 'Render visible items only', 30),
('React', 'advanced', 'Build a custom state management solution.', 'Use context and reducers', 30),
('React', 'advanced', 'Implement useReducer for complex state.', 'Use reducer pattern', 30),
('React', 'advanced', 'Create a higher-order component (HOC).', 'Wrap component logic', 30),
('React', 'advanced', 'Implement role-based access control.', 'Conditionally render routes', 30),
('React', 'advanced', 'Optimize performance using code splitting.', 'Use dynamic imports', 30),
('React', 'advanced', 'Create a reusable form validation system.', 'Use custom hooks', 30),
('React', 'advanced', 'Implement infinite scrolling.', 'Load data on scroll', 30),
('React', 'advanced', 'Handle race conditions in API calls.', 'Cancel outdated requests', 30),
('React', 'advanced', 'Build a compound component pattern.', 'Use shared internal state', 30),
('React', 'advanced', 'Implement server-side rendering conceptually.', 'Hydration and pre-rendering', 30),
('React', 'advanced', 'Design a plugin-based component system.', 'Use composition', 30),
('React', 'advanced', 'Create a type-safe React component system.', 'Use TypeScript generics', 30),
('React', 'advanced', 'Implement drag and drop functionality.', 'Use HTML5 drag API', 30),
('React', 'advanced', 'Create a real-time dashboard UI.', 'Use WebSockets', 30),
('React', 'advanced', 'Implement optimistic UI updates.', 'Update UI before response', 30),
('React', 'advanced', 'Design a reusable table component.', 'Use configuration-driven design', 30),
('React', 'advanced', 'Implement feature flag system.', 'Toggle features dynamically', 30),
('React', 'advanced', 'Create a micro-frontend-ready React app.', 'Isolate modules', 30),
('React', 'advanced', 'Build a scalable folder architecture.', 'Separate concerns', 30);
-- TypeScript Daily Tasks Questions

-- BEGINNER (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('TypeScript', 'beginner', 'Create a variable with explicit type annotation for a string.', 'Use let name: string = "value"', 10),
('TypeScript', 'beginner', 'Write a function that takes a number parameter and returns a number.', 'Use function name(param: number): number', 10),
('TypeScript', 'beginner', 'Create an interface for a User with name and age properties.', 'Use interface keyword with property types', 10),
('TypeScript', 'beginner', 'Define an array type that only contains numbers.', 'Use number[] or Array<number>', 10),
('TypeScript', 'beginner', 'Create a type alias for a string or number union type.', 'Use type Alias = string | number', 10),
('TypeScript', 'beginner', 'Write a function with an optional parameter.', 'Use ? after parameter name: param?: type', 10),
('TypeScript', 'beginner', 'Create an object that implements an interface.', 'Object must have all required interface properties', 10),
('TypeScript', 'beginner', 'Define a tuple type for [string, number].', 'Use [string, number] as the type', 10),
('TypeScript', 'beginner', 'Create an enum for days of the week.', 'Use enum DayOfWeek { Monday, Tuesday, ... }', 10),
('TypeScript', 'beginner', 'Write a function with a default parameter value.', 'Use param: type = defaultValue', 10);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('TypeScript', 'beginner', 'Declare a variable of type number and assign it a value.', 'Use : number for type annotation', 10),
('TypeScript', 'beginner', 'Create a function that accepts a string and returns its length.', 'Specify parameter and return types', 10),
('TypeScript', 'beginner', 'Define an array that can store only strings.', 'Use string[] type', 10),
('TypeScript', 'beginner', 'Create a tuple with a number and a string.', 'Use fixed-length tuple syntax', 10),
('TypeScript', 'beginner', 'Declare a variable using union types (string or number).', 'Use | operator', 10),
('TypeScript', 'beginner', 'Write a function that returns void.', 'Use void return type', 10),
('TypeScript', 'beginner', 'Create an interface for a User with name and age.', 'Use interface keyword', 10),
('TypeScript', 'beginner', 'Use a type alias to define a boolean type.', 'Use type keyword', 10),
('TypeScript', 'beginner', 'Declare an enum for user roles.', 'Use enum keyword', 10),
('TypeScript', 'beginner', 'Write a function with an optional parameter.', 'Use ? for optional parameters', 10),
('TypeScript', 'beginner', 'Create a readonly property in an interface.', 'Use readonly modifier', 10),
('TypeScript', 'beginner', 'Declare a variable with the any type.', 'Use any keyword', 10),
('TypeScript', 'beginner', 'Create a function that returns a boolean.', 'Specify boolean return type', 10),
('TypeScript', 'beginner', 'Define an object type with name and email.', 'Use inline type annotation', 10),
('TypeScript', 'beginner', 'Use type inference to assign a number.', 'Let TypeScript infer the type', 10),
('TypeScript', 'beginner', 'Create an array of numbers using generics.', 'Use Array<number>', 10),
('TypeScript', 'beginner', 'Write a function that accepts a tuple.', 'Define tuple in parameters', 10),
('TypeScript', 'beginner', 'Declare a variable with null and undefined types.', 'Use union with null | undefined', 10),
('TypeScript', 'beginner', 'Create a function that takes no arguments and returns a string.', 'Specify return type', 10),
('TypeScript', 'beginner', 'Use const assertion on an object.', 'Use as const syntax', 10);

-- INTERMEDIATE (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('TypeScript', 'intermediate', 'Create a generic function that works with any array type.', 'Use <T> to define generic type parameter', 20),
('TypeScript', 'intermediate', 'Write an interface that extends another interface.', 'Use interface Child extends Parent', 20),
('TypeScript', 'intermediate', 'Create a type guard function using is keyword.', 'Use param is Type as return type', 20),
('TypeScript', 'intermediate', 'Define a mapped type that makes all properties optional.', 'Use { [K in keyof T]?: T[K] }', 20),
('TypeScript', 'intermediate', 'Create a class with private and public members.', 'Use private and public access modifiers', 20),
('TypeScript', 'intermediate', 'Write a function using function overloading.', 'Define multiple function signatures', 20),
('TypeScript', 'intermediate', 'Create a discriminated union type.', 'Use a common literal type property for discrimination', 20),
('TypeScript', 'intermediate', 'Implement a generic interface with constraints.', 'Use <T extends SomeType>', 20),
('TypeScript', 'intermediate', 'Create a readonly array and object type.', 'Use readonly keyword or Readonly<T>', 20),
('TypeScript', 'intermediate', 'Write a type that extracts keys of a specific value type from an object.', 'Use conditional types with keyof', 20);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('TypeScript', 'intermediate', 'Create a generic function that returns the same type it receives.', 'Use <T> generic syntax', 20),
('TypeScript', 'intermediate', 'Implement an interface that extends another interface.', 'Use extends keyword', 20),
('TypeScript', 'intermediate', 'Create a function overload for a function with multiple signatures.', 'Define multiple function signatures', 20),
('TypeScript', 'intermediate', 'Use a mapped type to make all properties optional.', 'Use keyof and ?', 20),
('TypeScript', 'intermediate', 'Create a type guard function.', 'Use parameter is Type syntax', 20),
('TypeScript', 'intermediate', 'Use keyof operator on an interface.', 'Extract keys as union', 20),
('TypeScript', 'intermediate', 'Create a generic interface.', 'Use generics with interface', 20),
('TypeScript', 'intermediate', 'Implement a class with public, private, and protected members.', 'Use access modifiers', 20),
('TypeScript', 'intermediate', 'Create a utility type using Pick.', 'Pick selected properties', 20),
('TypeScript', 'intermediate', 'Use Partial utility type on an interface.', 'Partial<T>', 20),
('TypeScript', 'intermediate', 'Create a discriminated union.', 'Use literal types with unions', 20),
('TypeScript', 'intermediate', 'Write a function that accepts unknown type safely.', 'Use type narrowing', 20),
('TypeScript', 'intermediate', 'Use Record type to define object structure.', 'Record<Keys, Type>', 20),
('TypeScript', 'intermediate', 'Create a readonly array type.', 'Use ReadonlyArray<T>', 20),
('TypeScript', 'intermediate', 'Implement a class that implements an interface.', 'Use implements keyword', 20),
('TypeScript', 'intermediate', 'Use Exclude utility type.', 'Exclude<T, U>', 20),
('TypeScript', 'intermediate', 'Create a function using rest parameters with types.', 'Use ...args syntax', 20),
('TypeScript', 'intermediate', 'Define a function returning a Promise of number.', 'Use Promise<number>', 20),
('TypeScript', 'intermediate', 'Use ReturnType utility on a function.', 'ReturnType<typeof fn>', 20),
('TypeScript', 'intermediate', 'Create a type from a constant object.', 'Use typeof operator', 20);

-- ADVANCED (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('TypeScript', 'advanced', 'Implement a DeepReadonly type that recursively makes properties readonly.', 'Use conditional and mapped types recursively', 30),
('TypeScript', 'advanced', 'Create a type-safe event emitter using generics.', 'Map event names to their payload types', 30),
('TypeScript', 'advanced', 'Implement template literal types for route parsing.', 'Use template literal type inference', 30),
('TypeScript', 'advanced', 'Create a Promisify type that converts callback functions to promises.', 'Extract callback parameters and create Promise return', 30),
('TypeScript', 'advanced', 'Write a type that flattens nested object types.', 'Use recursive conditional types', 30),
('TypeScript', 'advanced', 'Implement a type-safe builder pattern.', 'Chain methods that update type state', 30),
('TypeScript', 'advanced', 'Create conditional types that infer function return types.', 'Use infer keyword in conditional types', 30),
('TypeScript', 'advanced', 'Implement a Pick type from scratch without using built-in.', 'Use mapped types with key filtering', 30),
('TypeScript', 'advanced', 'Create a type for deep partial objects.', 'Recursively apply Partial to nested objects', 30),
('TypeScript', 'advanced', 'Implement variadic tuple types for a zip function.', 'Use spread in tuple types', 30);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('TypeScript', 'advanced', 'Create a deep readonly utility type.', 'Use recursive mapped types', 30),
('TypeScript', 'advanced', 'Implement a generic constraint on a function.', 'Use extends keyword in generics', 30),
('TypeScript', 'advanced', 'Create a conditional type.', 'Use T extends U ? X : Y', 30),
('TypeScript', 'advanced', 'Implement a type-safe event emitter.', 'Use generics and mapped types', 30),
('TypeScript', 'advanced', 'Create a custom utility type similar to Omit.', 'Use Exclude and keyof', 30),
('TypeScript', 'advanced', 'Infer function argument types using conditional types.', 'Use infer keyword', 30),
('TypeScript', 'advanced', 'Create a strongly typed Redux action pattern.', 'Use discriminated unions', 30),
('TypeScript', 'advanced', 'Implement a fluent API with method chaining.', 'Return this from methods', 30),
('TypeScript', 'advanced', 'Create a type-safe API response wrapper.', 'Use generics and interfaces', 30),
('TypeScript', 'advanced', 'Build a recursive JSON type definition.', 'Use recursive type aliases', 30),
('TypeScript', 'advanced', 'Create a compile-time string literal validator.', 'Use template literal types', 30),
('TypeScript', 'advanced', 'Implement nominal typing using branding.', 'Use intersection with unique symbol', 30),
('TypeScript', 'advanced', 'Create a strongly typed form validation schema.', 'Use mapped and conditional types', 30),
('TypeScript', 'advanced', 'Design a type-safe dependency injection container.', 'Use generics and maps', 30),
('TypeScript', 'advanced', 'Implement a generic singleton pattern.', 'Use static generic methods', 30),
('TypeScript', 'advanced', 'Create a type that extracts async return types.', 'Use Awaited utility', 30),
('TypeScript', 'advanced', 'Model a finite state machine with types.', 'Use union and mapped types', 30),
('TypeScript', 'advanced', 'Create a type-safe middleware pipeline.', 'Use variadic tuple types', 30),
('TypeScript', 'advanced', 'Enforce exact object shapes using types.', 'Prevent excess properties', 30),
('TypeScript', 'advanced', 'Create a compile-time route parameter extractor.', 'Use template literal inference', 30);
-- HTML Daily Tasks Questions

-- BEGINNER (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('HTML', 'beginner', 'Create a basic HTML page with doctype, html, head, and body tags.', 'Start with <!DOCTYPE html>', 10),
('HTML', 'beginner', 'Add a heading (h1) and a paragraph (p) to your page.', 'Use <h1> for main heading', 10),
('HTML', 'beginner', 'Create an unordered list with 5 items.', 'Use <ul> with <li> items inside', 10),
('HTML', 'beginner', 'Add an image with alt text to your page.', 'Use <img src="" alt="">', 10),
('HTML', 'beginner', 'Create a hyperlink that opens in a new tab.', 'Use target="_blank" attribute', 10),
('HTML', 'beginner', 'Build a simple form with name and email inputs.', 'Use <form>, <input>, and <label> tags', 10),
('HTML', 'beginner', 'Add a table with 3 rows and 3 columns.', 'Use <table>, <tr>, <th>, <td>', 10),
('HTML', 'beginner', 'Create a div container with a paragraph inside.', 'Div is a generic container element', 10),
('HTML', 'beginner', 'Add a button element that says "Click Me".', 'Use <button>Click Me</button>', 10),
('HTML', 'beginner', 'Create a page with header, main, and footer sections.', 'Use semantic tags <header>, <main>, <footer>', 10);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('HTML', 'beginner', 'Create a basic HTML document structure.', 'Use <!DOCTYPE html>, html, head, body', 10),
('HTML', 'beginner', 'Add a heading with text using h1 tag.', 'Use <h1>', 10),
('HTML', 'beginner', 'Create a paragraph with some text.', 'Use <p>', 10),
('HTML', 'beginner', 'Add an image to a webpage.', 'Use <img src="">', 10),
('HTML', 'beginner', 'Create a hyperlink to another website.', 'Use <a href="">', 10),
('HTML', 'beginner', 'Create an unordered list with three items.', 'Use <ul> and <li>', 10),
('HTML', 'beginner', 'Create an ordered list with numbers.', 'Use <ol>', 10),
('HTML', 'beginner', 'Add a line break inside a paragraph.', 'Use <br>', 10),
('HTML', 'beginner', 'Create a horizontal line on the page.', 'Use <hr>', 10),
('HTML', 'beginner', 'Add a title to the webpage.', 'Use <title> inside <head>', 10),
('HTML', 'beginner', 'Create a button element.', 'Use <button>', 10),
('HTML', 'beginner', 'Create a text input field.', 'Use <input type="text">', 10),
('HTML', 'beginner', 'Create a password input field.', 'Use type="password"', 10),
('HTML', 'beginner', 'Create a checkbox input.', 'Use type="checkbox"', 10),
('HTML', 'beginner', 'Create a radio button input.', 'Use type="radio"', 10),
('HTML', 'beginner', 'Add a label for an input field.', 'Use <label for="">', 10),
('HTML', 'beginner', 'Create a form element.', 'Use <form>', 10),
('HTML', 'beginner', 'Add placeholder text to an input.', 'Use placeholder attribute', 10),
('HTML', 'beginner', 'Create a textarea input.', 'Use <textarea>', 10),
('HTML', 'beginner', 'Create a dropdown menu.', 'Use <select> and <option>', 10);

-- INTERMEDIATE (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('HTML', 'intermediate', 'Create a form with validation using required and pattern attributes.', 'Use pattern for regex validation', 20),
('HTML', 'intermediate', 'Build a navigation menu using nav and ul elements.', 'Wrap links in <nav> for semantics', 20),
('HTML', 'intermediate', 'Add a video element with controls and fallback text.', 'Use <video controls><source src=""></video>', 20),
('HTML', 'intermediate', 'Create an accessible form with proper labels and ARIA attributes.', 'Use for attribute to link labels to inputs', 20),
('HTML', 'intermediate', 'Build a card component using article, header, and section.', 'Article represents independent content', 20),
('HTML', 'intermediate', 'Create a details and summary element for collapsible content.', 'Details creates expandable sections', 20),
('HTML', 'intermediate', 'Add a figure with an image and figcaption.', 'Figure wraps self-contained content', 20),
('HTML', 'intermediate', 'Create a multi-step form using fieldset and legend.', 'Fieldset groups related form controls', 20),
('HTML', 'intermediate', 'Build a progress bar using the progress element.', 'Use <progress value="50" max="100">', 20),
('HTML', 'intermediate', 'Create a responsive image using srcset and sizes attributes.', 'Srcset provides different image sizes', 20);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('HTML', 'intermediate', 'Create a table with rows and columns.', 'Use table, tr, td', 20),
('HTML', 'intermediate', 'Add table headers to a table.', 'Use <th>', 20),
('HTML', 'intermediate', 'Merge table cells horizontally.', 'Use colspan attribute', 20),
('HTML', 'intermediate', 'Merge table cells vertically.', 'Use rowspan attribute', 20),
('HTML', 'intermediate', 'Create a semantic layout using header, main, footer.', 'Use semantic tags', 20),
('HTML', 'intermediate', 'Embed a video in a webpage.', 'Use <video>', 20),
('HTML', 'intermediate', 'Embed an audio file.', 'Use <audio>', 20),
('HTML', 'intermediate', 'Create a navigation menu using nav tag.', 'Use <nav>', 20),
('HTML', 'intermediate', 'Create an iframe to embed another webpage.', 'Use <iframe>', 20),
('HTML', 'intermediate', 'Use meta tags for responsive design.', 'Use viewport meta tag', 20),
('HTML', 'intermediate', 'Create a form with required validation.', 'Use required attribute', 20),
('HTML', 'intermediate', 'Use pattern attribute for input validation.', 'Use regex pattern', 20),
('HTML', 'intermediate', 'Create a download link for a file.', 'Use download attribute', 20),
('HTML', 'intermediate', 'Use figure and figcaption elements.', 'Wrap image and caption', 20),
('HTML', 'intermediate', 'Create an accessible image with alt text.', 'Use alt attribute', 20),
('HTML', 'intermediate', 'Use details and summary tags.', 'Expandable content', 20),
('HTML', 'intermediate', 'Create a progress bar.', 'Use <progress>', 20),
('HTML', 'intermediate', 'Create a meter element.', 'Use <meter>', 20),
('HTML', 'intermediate', 'Use datalist for input suggestions.', 'Use <datalist>', 20),
('HTML', 'intermediate', 'Create a favicon for a website.', 'Use link rel="icon"', 20);


-- ADVANCED (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('HTML', 'advanced', 'Create a custom data attribute system for a component.', 'Use data-* attributes for custom data', 30),
('HTML', 'advanced', 'Build a form with custom validation messages using setCustomValidity.', 'Use JavaScript with HTML5 validation API', 30),
('HTML', 'advanced', 'Create an accessible modal dialog using proper ARIA roles.', 'Use role="dialog" and aria-modal="true"', 30),
('HTML', 'advanced', 'Implement a skip navigation link for accessibility.', 'Hidden link that becomes visible on focus', 30),
('HTML', 'advanced', 'Create a content editable rich text area.', 'Use contenteditable="true" attribute', 30),
('HTML', 'advanced', 'Build a live region for screen reader announcements.', 'Use aria-live="polite" or "assertive"', 30),
('HTML', 'advanced', 'Create a custom autocomplete using datalist.', 'Datalist provides input suggestions', 30),
('HTML', 'advanced', 'Implement lazy loading for images and iframes.', 'Use loading="lazy" attribute', 30),
('HTML', 'advanced', 'Create a print-optimized page with proper meta tags.', 'Use media="print" for print stylesheets', 30),
('HTML', 'advanced', 'Build a fully accessible tab interface with ARIA.', 'Use role="tablist", "tab", and "tabpanel"', 30);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('HTML', 'advanced', 'Design a fully semantic HTML page structure.', 'Use only semantic tags', 30),
('HTML', 'advanced', 'Create an accessible form following WCAG guidelines.', 'Use labels and aria attributes', 30),
('HTML', 'advanced', 'Optimize HTML for SEO best practices.', 'Use semantic tags and meta tags', 30),
('HTML', 'advanced', 'Create a responsive image using srcset.', 'Use srcset and sizes', 30),
('HTML', 'advanced', 'Implement lazy loading for images.', 'Use loading attribute', 30),
('HTML', 'advanced', 'Create a custom data attribute and access it.', 'Use data-* attributes', 30),
('HTML', 'advanced', 'Design a multi-level navigation menu.', 'Use nested lists', 30),
('HTML', 'advanced', 'Create an HTML email-safe layout.', 'Use table-based layout', 30),
('HTML', 'advanced', 'Use ARIA roles for screen readers.', 'Use role attribute', 30),
('HTML', 'advanced', 'Create a contenteditable text editor.', 'Use contenteditable attribute', 30),
('HTML', 'advanced', 'Implement a responsive iframe.', 'Use CSS with iframe', 30),
('HTML', 'advanced', 'Create a modal structure using only HTML.', 'Use dialog element', 30),
('HTML', 'advanced', 'Implement form auto-complete handling.', 'Use autocomplete attribute', 30),
('HTML', 'advanced', 'Create a print-friendly HTML layout.', 'Use media attributes', 30),
('HTML', 'advanced', 'Use picture element for art direction.', 'Use <picture>', 30),
('HTML', 'advanced', 'Create an accessible navigation landmark.', 'Use nav and aria-label', 30),
('HTML', 'advanced', 'Optimize HTML loading performance.', 'Reduce DOM depth', 30),
('HTML', 'advanced', 'Implement microdata for SEO.', 'Use itemscope and itemprop', 30),
('HTML', 'advanced', 'Create a fallback strategy for unsupported media.', 'Use multiple sources', 30),
('HTML', 'advanced', 'Design a skeleton loader using HTML.', 'Use semantic placeholders', 30);
 -- CSS Daily Tasks Questions

-- BEGINNER (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('CSS', 'beginner', 'Change the background color of a div to blue.', 'Use background-color property', 10),
('CSS', 'beginner', 'Set the font size of a paragraph to 18px.', 'Use font-size: 18px', 10),
('CSS', 'beginner', 'Add padding and margin to a button.', 'Padding is inside, margin is outside', 10),
('CSS', 'beginner', 'Create a class that makes text bold and red.', 'Use font-weight and color properties', 10),
('CSS', 'beginner', 'Center text inside a heading element.', 'Use text-align: center', 10),
('CSS', 'beginner', 'Add a border around an image.', 'Use border: 2px solid color', 10),
('CSS', 'beginner', 'Change the width and height of a div.', 'Use width and height properties', 10),
('CSS', 'beginner', 'Apply a hover effect that changes background color.', 'Use selector:hover { }', 10),
('CSS', 'beginner', 'Remove the underline from links.', 'Use text-decoration: none', 10),
('CSS', 'beginner', 'Set a background image on the body.', 'Use background-image: url()', 10);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('CSS', 'beginner', 'Apply a background color to a div.', 'Use background-color property', 10),
('CSS', 'beginner', 'Change text color of a paragraph.', 'Use color property', 10),
('CSS', 'beginner', 'Set font size of text.', 'Use font-size property', 10),
('CSS', 'beginner', 'Center text inside a div.', 'Use text-align: center', 10),
('CSS', 'beginner', 'Add margin to an element.', 'Use margin property', 10),
('CSS', 'beginner', 'Add padding inside an element.', 'Use padding property', 10),
('CSS', 'beginner', 'Set width and height of a box.', 'Use width and height', 10),
('CSS', 'beginner', 'Add a border to an element.', 'Use border property', 10),
('CSS', 'beginner', 'Make text bold.', 'Use font-weight', 10),
('CSS', 'beginner', 'Change font family of text.', 'Use font-family', 10),
('CSS', 'beginner', 'Remove underline from a link.', 'Use text-decoration: none', 10),
('CSS', 'beginner', 'Align an element to the center using margin.', 'Use margin: auto', 10),
('CSS', 'beginner', 'Make an image responsive.', 'Use max-width: 100%', 10),
('CSS', 'beginner', 'Change background color on hover.', 'Use :hover pseudo-class', 10),
('CSS', 'beginner', 'Hide an element from display.', 'Use display: none', 10),
('CSS', 'beginner', 'Make a list display horizontally.', 'Use display: inline or flex', 10),
('CSS', 'beginner', 'Change cursor to pointer.', 'Use cursor property', 10),
('CSS', 'beginner', 'Set line height for text.', 'Use line-height', 10),
('CSS', 'beginner', 'Add box shadow to an element.', 'Use box-shadow', 10),
('CSS', 'beginner', 'Make text uppercase.', 'Use text-transform', 10);

-- INTERMEDIATE (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('CSS', 'intermediate', 'Create a flexbox container that centers its children.', 'Use display: flex with justify-content and align-items', 20),
('CSS', 'intermediate', 'Build a two-column layout using CSS Grid.', 'Use display: grid with grid-template-columns', 20),
('CSS', 'intermediate', 'Add a smooth transition effect to a button hover.', 'Use transition property with duration', 20),
('CSS', 'intermediate', 'Create a responsive design using media queries.', 'Use @media (max-width: 768px) { }', 20),
('CSS', 'intermediate', 'Position an element absolutely within its parent.', 'Parent needs position: relative', 20),
('CSS', 'intermediate', 'Create a gradient background.', 'Use linear-gradient or radial-gradient', 20),
('CSS', 'intermediate', 'Add a box shadow to a card component.', 'Use box-shadow property', 20),
('CSS', 'intermediate', 'Create a navigation bar that sticks to the top.', 'Use position: sticky or fixed', 20),
('CSS', 'intermediate', 'Build a CSS-only dropdown menu.', 'Use :hover on parent to show child', 20),
('CSS', 'intermediate', 'Create custom CSS variables and use them.', 'Define with --name, use with var(--name)', 20);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('CSS', 'intermediate', 'Create a flex container.', 'Use display: flex', 20),
('CSS', 'intermediate', 'Align items horizontally using flexbox.', 'Use justify-content', 20),
('CSS', 'intermediate', 'Align items vertically using flexbox.', 'Use align-items', 20),
('CSS', 'intermediate', 'Create a responsive grid layout.', 'Use CSS Grid', 20),
('CSS', 'intermediate', 'Create a two-column layout.', 'Use grid or flex', 20),
('CSS', 'intermediate', 'Implement sticky header.', 'Use position: sticky', 20),
('CSS', 'intermediate', 'Create a dropdown menu using CSS.', 'Use :hover and position', 20),
('CSS', 'intermediate', 'Animate an element using transition.', 'Use transition property', 20),
('CSS', 'intermediate', 'Create a keyframe animation.', 'Use @keyframes', 20),
('CSS', 'intermediate', 'Use media queries for responsiveness.', 'Use @media rule', 20),
('CSS', 'intermediate', 'Create a card layout.', 'Use box model and shadow', 20),
('CSS', 'intermediate', 'Control element stacking order.', 'Use z-index', 20),
('CSS', 'intermediate', 'Create a circular image.', 'Use border-radius: 50%', 20),
('CSS', 'intermediate', 'Use pseudo-elements before and after.', 'Use ::before and ::after', 20),
('CSS', 'intermediate', 'Create a modal overlay.', 'Use position: fixed', 20),
('CSS', 'intermediate', 'Use overflow to control scrolling.', 'Use overflow property', 20),
('CSS', 'intermediate', 'Implement CSS variables.', 'Use --variable-name', 20),
('CSS', 'intermediate', 'Style form input focus state.', 'Use :focus pseudo-class', 20),
('CSS', 'intermediate', 'Create an image overlay effect.', 'Use position and opacity', 20),
('CSS', 'intermediate', 'Implement responsive typography.', 'Use relative units', 20);

-- ADVANCED (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('CSS', 'advanced', 'Create a CSS animation for a loading spinner.', 'Use @keyframes with transform: rotate', 30),
('CSS', 'advanced', 'Build a responsive grid that changes columns based on screen size.', 'Use minmax() with auto-fit or auto-fill', 30),
('CSS', 'advanced', 'Implement a dark mode theme using CSS custom properties.', 'Switch variables based on class or attribute', 30),
('CSS', 'advanced', 'Create a perspective 3D card flip effect.', 'Use transform-style: preserve-3d and rotateY', 30),
('CSS', 'advanced', 'Build a masonry layout using CSS Grid.', 'Use grid-row spanning for different heights', 30),
('CSS', 'advanced', 'Create a clip-path animation for revealing content.', 'Animate clip-path property', 30),
('CSS', 'advanced', 'Implement scroll-snap for a carousel.', 'Use scroll-snap-type and scroll-snap-align', 30),
('CSS', 'advanced', 'Create a glassmorphism effect.', 'Use backdrop-filter: blur with transparency', 30),
('CSS', 'advanced', 'Build a CSS-only toggle switch.', 'Use checkbox with :checked pseudo-class', 30),
('CSS', 'advanced', 'Create complex shapes using clip-path polygon.', 'Define points as percentage coordinates', 30);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('CSS', 'advanced', 'Build a full layout using CSS Grid.', 'Use grid-template-areas', 30),
('CSS', 'advanced', 'Create a dark mode using CSS variables.', 'Toggle variables', 30),
('CSS', 'advanced', 'Implement a CSS-only accordion.', 'Use checkbox hack', 30),
('CSS', 'advanced', 'Create a complex animation timeline.', 'Use multiple keyframes', 30),
('CSS', 'advanced', 'Design a glassmorphism UI.', 'Use backdrop-filter', 30),
('CSS', 'advanced', 'Optimize CSS for performance.', 'Reduce repaint and reflow', 30),
('CSS', 'advanced', 'Create a masonry layout.', 'Use grid-auto-flow', 30),
('CSS', 'advanced', 'Implement a responsive navbar.', 'Combine flex and media queries', 30),
('CSS', 'advanced', 'Create a loading spinner animation.', 'Use keyframes and transform', 30),
('CSS', 'advanced', 'Use clamp() for responsive sizing.', 'Use clamp(min, preferred, max)', 30),
('CSS', 'advanced', 'Create a parallax scrolling effect.', 'Use background-attachment', 30),
('CSS', 'advanced', 'Design accessible focus styles.', 'Use :focus-visible', 30),
('CSS', 'advanced', 'Implement container queries.', 'Use @container', 30),
('CSS', 'advanced', 'Create a CSS-only tooltip.', 'Use pseudo-elements', 30),
('CSS', 'advanced', 'Build a responsive image gallery.', 'Use grid and auto-fit', 30),
('CSS', 'advanced', 'Create a neumorphism UI component.', 'Use layered shadows', 30),
('CSS', 'advanced', 'Implement text gradient effect.', 'Use background-clip: text', 30),
('CSS', 'advanced', 'Create an adaptive layout without media queries.', 'Use flex and grid auto', 30),
('CSS', 'advanced', 'Design a CSS-only toggle switch.', 'Use input and labels', 30),
('CSS', 'advanced', 'Build a print-specific stylesheet.', 'Use print media queries', 30);
-- C Programming Daily Tasks Questions

-- BEGINNER (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C', 'beginner', 'Write a program that prints "Hello, World!" to the console.', 'Use printf() from stdio.h', 10),
('C', 'beginner', 'Declare an integer variable and print its value.', 'Use int and printf with %d', 10),
('C', 'beginner', 'Write a program that adds two numbers entered by user.', 'Use scanf() to read input', 10),
('C', 'beginner', 'Create a program that checks if a number is positive or negative.', 'Use if-else statement', 10),
('C', 'beginner', 'Write a for loop that prints numbers 1 to 10.', 'Use for(int i=1; i<=10; i++)', 10),
('C', 'beginner', 'Create an array of 5 integers and print all elements.', 'Use int arr[5] and loop to print', 10),
('C', 'beginner', 'Write a function that returns the square of a number.', 'Use return num * num', 10),
('C', 'beginner', 'Create a program using a while loop to sum numbers.', 'Initialize sum, loop while condition', 10),
('C', 'beginner', 'Write a program that finds the largest of three numbers.', 'Use nested if-else or logical operators', 10),
('C', 'beginner', 'Create a program that calculates factorial using a loop.', 'Multiply 1*2*3*...*n', 10);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C', 'beginner', 'Write a C program that prints Hello World.', 'Use printf()', 10),
('C', 'beginner', 'Declare and initialize an integer variable.', 'Use int keyword', 10),
('C', 'beginner', 'Take user input using scanf.', 'Use & operator', 10),
('C', 'beginner', 'Add two numbers entered by the user.', 'Use arithmetic operators', 10),
('C', 'beginner', 'Check whether a number is even or odd.', 'Use modulo operator', 10),
('C', 'beginner', 'Write a program to find the largest of two numbers.', 'Use if-else', 10),
('C', 'beginner', 'Write a program to print numbers from 1 to 10.', 'Use for loop', 10),
('C', 'beginner', 'Write a program to calculate the factorial of a number.', 'Use loop', 10),
('C', 'beginner', 'Declare an array of integers.', 'Use square brackets', 10),
('C', 'beginner', 'Access elements of an array.', 'Use index positions', 10),
('C', 'beginner', 'Find the sum of elements in an array.', 'Use loop', 10),
('C', 'beginner', 'Declare a string using char array.', 'Use char[]', 10),
('C', 'beginner', 'Find the length of a string.', 'Use strlen()', 10),
('C', 'beginner', 'Copy one string to another.', 'Use strcpy()', 10),
('C', 'beginner', 'Compare two strings.', 'Use strcmp()', 10),
('C', 'beginner', 'Create a simple function.', 'Define and call function', 10),
('C', 'beginner', 'Pass arguments to a function.', 'Use parameters', 10),
('C', 'beginner', 'Return a value from a function.', 'Use return keyword', 10),
('C', 'beginner', 'Use switch-case statement.', 'Use switch keyword', 10),
('C', 'beginner', 'Demonstrate use of break and continue.', 'Use inside loops', 10);

-- INTERMEDIATE (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C', 'intermediate', 'Write a program using pointers to swap two numbers.', 'Pass addresses and dereference with *', 20),
('C', 'intermediate', 'Create a function that reverses a string in place.', 'Swap characters from both ends', 20),
('C', 'intermediate', 'Implement a structure for a student with name and grade.', 'Use struct keyword', 20),
('C', 'intermediate', 'Write a program that dynamically allocates an array.', 'Use malloc() and free()', 20),
('C', 'intermediate', 'Create a recursive function to calculate Fibonacci.', 'fib(n) = fib(n-1) + fib(n-2)', 20),
('C', 'intermediate', 'Implement a simple bubble sort algorithm.', 'Compare and swap adjacent elements', 20),
('C', 'intermediate', 'Write a program that reads and writes to a file.', 'Use fopen, fprintf, fscanf, fclose', 20),
('C', 'intermediate', 'Create a function that counts words in a string.', 'Count space-separated tokens', 20),
('C', 'intermediate', 'Implement a linear search algorithm.', 'Loop through array comparing each element', 20),
('C', 'intermediate', 'Write a program using command line arguments.', 'Use argc and argv in main()', 20);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C', 'intermediate', 'Write a program using pointers.', 'Use * operator', 20),
('C', 'intermediate', 'Swap two numbers using pointers.', 'Pass addresses', 20),
('C', 'intermediate', 'Create a dynamic array using malloc.', 'Use malloc()', 20),
('C', 'intermediate', 'Resize a dynamic array using realloc.', 'Use realloc()', 20),
('C', 'intermediate', 'Free dynamically allocated memory.', 'Use free()', 20),
('C', 'intermediate', 'Write a program using structures.', 'Use struct keyword', 20),
('C', 'intermediate', 'Access structure members using pointer.', 'Use -> operator', 20),
('C', 'intermediate', 'Write a program using union.', 'Use union keyword', 20),
('C', 'intermediate', 'Create and use enum.', 'Use enum keyword', 20),
('C', 'intermediate', 'Pass structure to a function.', 'Use struct parameters', 20),
('C', 'intermediate', 'Implement recursion to calculate factorial.', 'Function calls itself', 20),
('C', 'intermediate', 'Write a program to reverse a string.', 'Use loop or pointers', 20),
('C', 'intermediate', 'Sort an array using bubble sort.', 'Compare adjacent elements', 20),
('C', 'intermediate', 'Search an element using linear search.', 'Iterate array', 20),
('C', 'intermediate', 'Read from a file.', 'Use fopen and fscanf', 20),
('C', 'intermediate', 'Write data to a file.', 'Use fprintf()', 20),
('C', 'intermediate', 'Use command-line arguments.', 'Use argc and argv', 20),
('C', 'intermediate', 'Handle errors using perror.', 'Use perror()', 20),
('C', 'intermediate', 'Create a header file.', 'Use .h extension', 20),
('C', 'intermediate', 'Use static variables.', 'Use static keyword', 20);

-- ADVANCED (10 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C', 'advanced', 'Implement a linked list with insert and delete operations.', 'Use struct for node with data and next pointer', 30),
('C', 'advanced', 'Create a binary search tree with insertion.', 'Recursively insert based on comparison', 30),
('C', 'advanced', 'Implement a stack using an array with push/pop.', 'Track top index for operations', 30),
('C', 'advanced', 'Write a program using function pointers.', 'Declare as return_type (*name)(params)', 30),
('C', 'advanced', 'Implement a hash table with chaining.', 'Use array of linked lists for collisions', 30),
('C', 'advanced', 'Create a program that handles signals.', 'Use signal() to register handlers', 30),
('C', 'advanced', 'Implement a memory pool allocator.', 'Pre-allocate block, manage free list', 30),
('C', 'advanced', 'Write a multi-threaded program using pthreads.', 'Use pthread_create and pthread_join', 30),
('C', 'advanced', 'Implement quicksort algorithm.', 'Partition around pivot recursively', 30),
('C', 'advanced', 'Create a simple shell that executes commands.', 'Use fork(), exec(), and waitpid()', 30);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C', 'advanced', 'Implement a stack using arrays.', 'Use push and pop', 30),
('C', 'advanced', 'Implement a queue using arrays.', 'Use front and rear', 30),
('C', 'advanced', 'Implement a linked list.', 'Use struct and pointers', 30),
('C', 'advanced', 'Insert a node in a linked list.', 'Handle pointer links', 30),
('C', 'advanced', 'Delete a node from a linked list.', 'Adjust pointers', 30),
('C', 'advanced', 'Reverse a linked list.', 'Iterative or recursive', 30),
('C', 'advanced', 'Detect a loop in a linked list.', 'Use fast and slow pointers', 30),
('C', 'advanced', 'Implement binary search.', 'Divide and conquer', 30),
('C', 'advanced', 'Implement merge sort.', 'Recursive sorting', 30),
('C', 'advanced', 'Implement quick sort.', 'Use partition logic', 30),
('C', 'advanced', 'Implement a binary tree.', 'Use node structure', 30),
('C', 'advanced', 'Traverse a binary tree.', 'Inorder, preorder, postorder', 30),
('C', 'advanced', 'Implement a hash table.', 'Use hashing technique', 30),
('C', 'advanced', 'Create a custom memory allocator.', 'Use heap management', 30),
('C', 'advanced', 'Use bitwise operators for flags.', 'Use &, |, ^', 30),
('C', 'advanced', 'Implement a circular linked list.', 'Last node points to head', 30),
('C', 'advanced', 'Build a mini command-line shell.', 'Use system calls', 30),
('C', 'advanced', 'Handle signals in C.', 'Use signal handling', 30),
('C', 'advanced', 'Implement multithreading using pthreads.', 'Use pthread library', 30),
('C', 'advanced', 'Optimize C code for performance.', 'Reduce memory and CPU usage', 30);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Node.js', 'beginner', 'Create a simple Node.js script that prints text to console.', 'Use console.log()', 10),
('Node.js', 'beginner', 'Initialize a Node.js project using npm.', 'Use npm init', 10),
('Node.js', 'beginner', 'Install a package using npm.', 'Use npm install', 10),
('Node.js', 'beginner', 'Import a built-in Node.js module.', 'Use require()', 10),
('Node.js', 'beginner', 'Create a basic HTTP server.', 'Use http module', 10),
('Node.js', 'beginner', 'Send a plain text response from server.', 'Use res.end()', 10),
('Node.js', 'beginner', 'Read a file asynchronously.', 'Use fs.readFile()', 10),
('Node.js', 'beginner', 'Write data to a file.', 'Use fs.writeFile()', 10),
('Node.js', 'beginner', 'Append data to a file.', 'Use fs.appendFile()', 10),
('Node.js', 'beginner', 'Get current directory path.', 'Use __dirname', 10),
('Node.js', 'beginner', 'Get current file path.', 'Use __filename', 10),
('Node.js', 'beginner', 'Use environment variables.', 'Use process.env', 10),
('Node.js', 'beginner', 'Create and use a custom module.', 'Use module.exports', 10),
('Node.js', 'beginner', 'Handle command-line arguments.', 'Use process.argv', 10),
('Node.js', 'beginner', 'Create a simple Express server.', 'Use express()', 10),
('Node.js', 'beginner', 'Create a GET route in Express.', 'Use app.get()', 10),
('Node.js', 'beginner', 'Send JSON response from Express.', 'Use res.json()', 10),
('Node.js', 'beginner', 'Use middleware in Express.', 'Use app.use()', 10),
('Node.js', 'beginner', 'Serve static files using Express.', 'Use express.static()', 10),
('Node.js', 'beginner', 'Handle basic errors in Express.', 'Use error handler', 10);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Node.js', 'intermediate', 'Handle asynchronous code using Promises.', 'Use .then()', 20),
('Node.js', 'intermediate', 'Use async and await syntax.', 'Wrap in async function', 20),
('Node.js', 'intermediate', 'Create RESTful API endpoints.', 'Use HTTP methods', 20),
('Node.js', 'intermediate', 'Parse JSON request body.', 'Use express.json()', 20),
('Node.js', 'intermediate', 'Handle URL parameters.', 'Use req.params', 20),
('Node.js', 'intermediate', 'Handle query parameters.', 'Use req.query', 20),
('Node.js', 'intermediate', 'Implement error-handling middleware.', 'Use four parameters', 20),
('Node.js', 'intermediate', 'Connect Node.js with MongoDB.', 'Use mongoose', 20),
('Node.js', 'intermediate', 'Define a Mongoose schema.', 'Use Schema()', 20),
('Node.js', 'intermediate', 'Perform CRUD operations with MongoDB.', 'Use model methods', 20),
('Node.js', 'intermediate', 'Use dotenv to manage environment variables.', 'Use dotenv package', 20),
('Node.js', 'intermediate', 'Implement request validation.', 'Use validation middleware', 20),
('Node.js', 'intermediate', 'Implement JWT authentication.', 'Use jsonwebtoken', 20),
('Node.js', 'intermediate', 'Hash passwords securely.', 'Use bcrypt', 20),
('Node.js', 'intermediate', 'Implement pagination in API.', 'Use limit and skip', 20),
('Node.js', 'intermediate', 'Implement rate limiting.', 'Use middleware', 20),
('Node.js', 'intermediate', 'Handle file uploads.', 'Use multer', 20),
('Node.js', 'intermediate', 'Implement logging system.', 'Use logging library', 20),
('Node.js', 'intermediate', 'Use CORS in Express.', 'Use cors middleware', 20),
('Node.js', 'intermediate', 'Write unit tests for APIs.', 'Use testing framework', 20);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Node.js', 'advanced', 'Design a scalable Node.js architecture.', 'Separate layers', 30),
('Node.js', 'advanced', 'Implement role-based access control.', 'Use middleware', 30),
('Node.js', 'advanced', 'Handle API versioning.', 'Use route prefixes', 30),
('Node.js', 'advanced', 'Implement refresh token authentication.', 'Use JWT strategy', 30),
('Node.js', 'advanced', 'Build a real-time chat server.', 'Use WebSockets', 30),
('Node.js', 'advanced', 'Use Socket.IO for real-time events.', 'Use socket events', 30),
('Node.js', 'advanced', 'Implement background jobs.', 'Use job queues', 30),
('Node.js', 'advanced', 'Use Redis for caching.', 'Use Redis client', 30),
('Node.js', 'advanced', 'Optimize API performance.', 'Use caching and async', 30),
('Node.js', 'advanced', 'Implement API security best practices.', 'Sanitize inputs', 30),
('Node.js', 'advanced', 'Handle graceful shutdown.', 'Close server properly', 30),
('Node.js', 'advanced', 'Use clustering for scalability.', 'Use cluster module', 30),
('Node.js', 'advanced', 'Implement event-driven architecture.', 'Use EventEmitter', 30),
('Node.js', 'advanced', 'Create a microservices-based backend.', 'Service separation', 30),
('Node.js', 'advanced', 'Implement API gateway pattern.', 'Central entry point', 30),
('Node.js', 'advanced', 'Implement circuit breaker pattern.', 'Fail fast strategy', 30),
('Node.js', 'advanced', 'Monitor Node.js application.', 'Use monitoring tools', 30),
('Node.js', 'advanced', 'Handle memory leaks in Node.js.', 'Profile heap usage', 30),
('Node.js', 'advanced', 'Deploy Node.js app to production.', 'Use process manager', 30),
('Node.js', 'advanced', 'Design fault-tolerant Node.js system.', 'Use retries and fallbacks', 30);

INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C++', 'beginner', 'Write a C++ program that prints Hello World.', 'Use cout', 10),
('C++', 'beginner', 'Declare and initialize an integer variable.', 'Use int keyword', 10),
('C++', 'beginner', 'Take user input using cin.', 'Use cin >>', 10),
('C++', 'beginner', 'Add two numbers entered by the user.', 'Use arithmetic operators', 10),
('C++', 'beginner', 'Check whether a number is even or odd.', 'Use modulo operator', 10),
('C++', 'beginner', 'Write a program using if-else statement.', 'Use if keyword', 10),
('C++', 'beginner', 'Write a program using switch-case.', 'Use switch statement', 10),
('C++', 'beginner', 'Print numbers from 1 to 10 using loop.', 'Use for loop', 10),
('C++', 'beginner', 'Declare and access an array.', 'Use index positions', 10),
('C++', 'beginner', 'Find the size of an array.', 'Use sizeof operator', 10),
('C++', 'beginner', 'Create and use a function.', 'Define and call function', 10),
('C++', 'beginner', 'Return a value from a function.', 'Use return keyword', 10),
('C++', 'beginner', 'Declare a string and print it.', 'Use string class', 10),
('C++', 'beginner', 'Find length of a string.', 'Use length() function', 10),
('C++', 'beginner', 'Concatenate two strings.', 'Use + operator', 10),
('C++', 'beginner', 'Use while loop.', 'Use while keyword', 10),
('C++', 'beginner', 'Create a simple class.', 'Use class keyword', 10),
('C++', 'beginner', 'Create an object of a class.', 'Instantiate class', 10),
('C++', 'beginner', 'Use public and private access specifiers.', 'Access control', 10),
('C++', 'beginner', 'Demonstrate constructor usage.', 'Same name as class', 10);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C++', 'intermediate', 'Implement function overloading.', 'Same function name', 20),
('C++', 'intermediate', 'Implement operator overloading.', 'Redefine operators', 20),
('C++', 'intermediate', 'Implement inheritance.', 'Use : operator', 20),
('C++', 'intermediate', 'Override a base class method.', 'Use virtual keyword', 20),
('C++', 'intermediate', 'Implement polymorphism.', 'Base pointer derived object', 20),
('C++', 'intermediate', 'Use virtual destructor.', 'Prevent memory leaks', 20),
('C++', 'intermediate', 'Use pointers in C++.', 'Use * operator', 20),
('C++', 'intermediate', 'Use references in C++.', 'Use & symbol', 20),
('C++', 'intermediate', 'Implement dynamic memory allocation.', 'Use new and delete', 20),
('C++', 'intermediate', 'Use STL vector container.', 'Use vector', 20),
('C++', 'intermediate', 'Iterate vector using iterator.', 'Use iterators', 20),
('C++', 'intermediate', 'Use STL map container.', 'Key-value storage', 20),
('C++', 'intermediate', 'Use STL set container.', 'Unique elements', 20),
('C++', 'intermediate', 'Sort elements using STL.', 'Use sort()', 20),
('C++', 'intermediate', 'Search element using binary search.', 'Use binary_search()', 20),
('C++', 'intermediate', 'Read data from a file.', 'Use ifstream', 20),
('C++', 'intermediate', 'Write data to a file.', 'Use ofstream', 20),
('C++', 'intermediate', 'Handle exceptions using try-catch.', 'Use try block', 20),
('C++', 'intermediate', 'Use namespaces.', 'Avoid naming conflicts', 20),
('C++', 'intermediate', 'Use const correctness.', 'Prevent modification', 20);

INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C++', 'advanced', 'Implement a linked list.', 'Use pointers and structs', 30),
('C++', 'advanced', 'Implement stack using array.', 'Use push and pop', 30),
('C++', 'advanced', 'Implement queue using array.', 'Use front and rear', 30),
('C++', 'advanced', 'Implement binary search tree.', 'Use node structure', 30),
('C++', 'advanced', 'Traverse a binary tree.', 'Inorder, preorder, postorder', 30),
('C++', 'advanced', 'Implement depth-first search.', 'Use recursion or stack', 30),
('C++', 'advanced', 'Implement breadth-first search.', 'Use queue', 30),
('C++', 'advanced', 'Implement merge sort.', 'Divide and conquer', 30),
('C++', 'advanced', 'Implement quick sort.', 'Use partition logic', 30),
('C++', 'advanced', 'Implement graph using adjacency list.', 'Use vector of vectors', 30),
('C++', 'advanced', 'Detect cycle in a graph.', 'Use visited array', 30),
('C++', 'advanced', 'Implement smart pointers.', 'Use unique_ptr and shared_ptr', 30),
('C++', 'advanced', 'Use RAII principle.', 'Resource management', 30),
('C++', 'advanced', 'Implement multithreading.', 'Use std::thread', 30),
('C++', 'advanced', 'Synchronize threads using mutex.', 'Use std::mutex', 30),
('C++', 'advanced', 'Optimize C++ code performance.', 'Reduce copies and overhead', 30),
('C++', 'advanced', 'Implement move semantics.', 'Use std::move', 30),
('C++', 'advanced', 'Design a memory-efficient system.', 'Optimize allocation', 30),
('C++', 'advanced', 'Build a scalable C++ application.', 'Modular design', 30),
('C++', 'advanced', 'Use profiling tools for optimization.', 'Measure performance', 30);
 