INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C++', 'beginner', 'Write a C++ program that prints Hello World.', 'Use cout', 10),
('C++', 'beginner', 'Declare and initialize an integer variable.', 'Use int keyword', 10),
('C++', 'beginner', 'Take user input using cin.', 'Use cin >>', 10),
('C++', 'beginner', 'Add two numbers entered by the user.', 'Use arithmetic operators', 10),
('C++', 'beginner', 'Check whether a number is even or odd.', 'Use modulo operator', 10),
('C++', 'beginner', 'Write a program using if-else statement.', 'Use if keyword', 10),
('C++', 'beginner', 'Write a program using switch-case.', 'Use switch statement', 10),
('C++', 'beginner', 'Print numbers from 1 to 10 using loop.', 'Use for loop', 10),
('C++', 'beginner', 'Declare and access an array.', 'Use index positions', 10),
('C++', 'beginner', 'Find the size of an array.', 'Use sizeof operator', 10),
('C++', 'beginner', 'Create and use a function.', 'Define and call function', 10),
('C++', 'beginner', 'Return a value from a function.', 'Use return keyword', 10),
('C++', 'beginner', 'Declare a string and print it.', 'Use string class', 10),
('C++', 'beginner', 'Find length of a string.', 'Use length() function', 10),
('C++', 'beginner', 'Concatenate two strings.', 'Use + operator', 10),
('C++', 'beginner', 'Use while loop.', 'Use while keyword', 10),
('C++', 'beginner', 'Create a simple class.', 'Use class keyword', 10),
('C++', 'beginner', 'Create an object of a class.', 'Instantiate class', 10),
('C++', 'beginner', 'Use public and private access specifiers.', 'Access control', 10),
('C++', 'beginner', 'Demonstrate constructor usage.', 'Same name as class', 10);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C++', 'intermediate', 'Implement function overloading.', 'Same function name', 20),
('C++', 'intermediate', 'Implement operator overloading.', 'Redefine operators', 20),
('C++', 'intermediate', 'Implement inheritance.', 'Use : operator', 20),
('C++', 'intermediate', 'Override a base class method.', 'Use virtual keyword', 20),
('C++', 'intermediate', 'Implement polymorphism.', 'Base pointer derived object', 20),
('C++', 'intermediate', 'Use virtual destructor.', 'Prevent memory leaks', 20),
('C++', 'intermediate', 'Use pointers in C++.', 'Use * operator', 20),
('C++', 'intermediate', 'Use references in C++.', 'Use & symbol', 20),
('C++', 'intermediate', 'Implement dynamic memory allocation.', 'Use new and delete', 20),
('C++', 'intermediate', 'Use STL vector container.', 'Use vector', 20),
('C++', 'intermediate', 'Iterate vector using iterator.', 'Use iterators', 20),
('C++', 'intermediate', 'Use STL map container.', 'Key-value storage', 20),
('C++', 'intermediate', 'Use STL set container.', 'Unique elements', 20),
('C++', 'intermediate', 'Sort elements using STL.', 'Use sort()', 20),
('C++', 'intermediate', 'Search element using binary search.', 'Use binary_search()', 20),
('C++', 'intermediate', 'Read data from a file.', 'Use ifstream', 20),
('C++', 'intermediate', 'Write data to a file.', 'Use ofstream', 20),
('C++', 'intermediate', 'Handle exceptions using try-catch.', 'Use try block', 20),
('C++', 'intermediate', 'Use namespaces.', 'Avoid naming conflicts', 20),
('C++', 'intermediate', 'Use const correctness.', 'Prevent modification', 20);

INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('C++', 'advanced', 'Implement a linked list.', 'Use pointers and structs', 30),
('C++', 'advanced', 'Implement stack using array.', 'Use push and pop', 30),
('C++', 'advanced', 'Implement queue using array.', 'Use front and rear', 30),
('C++', 'advanced', 'Implement binary search tree.', 'Use node structure', 30),
('C++', 'advanced', 'Traverse a binary tree.', 'Inorder, preorder, postorder', 30),
('C++', 'advanced', 'Implement depth-first search.', 'Use recursion or stack', 30),
('C++', 'advanced', 'Implement breadth-first search.', 'Use queue', 30),
('C++', 'advanced', 'Implement merge sort.', 'Divide and conquer', 30),
('C++', 'advanced', 'Implement quick sort.', 'Use partition logic', 30),
('C++', 'advanced', 'Implement graph using adjacency list.', 'Use vector of vectors', 30),
('C++', 'advanced', 'Detect cycle in a graph.', 'Use visited array', 30),
('C++', 'advanced', 'Implement smart pointers.', 'Use unique_ptr and shared_ptr', 30),
('C++', 'advanced', 'Use RAII principle.', 'Resource management', 30),
('C++', 'advanced', 'Implement multithreading.', 'Use std::thread', 30),
('C++', 'advanced', 'Synchronize threads using mutex.', 'Use std::mutex', 30),
('C++', 'advanced', 'Optimize C++ code performance.', 'Reduce copies and overhead', 30),
('C++', 'advanced', 'Implement move semantics.', 'Use std::move', 30),
('C++', 'advanced', 'Design a memory-efficient system.', 'Optimize allocation', 30),
('C++', 'advanced', 'Build a scalable C++ application.', 'Modular design', 30),
('C++', 'advanced', 'Use profiling tools for optimization.', 'Measure performance', 30);
 