INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Node.js', 'beginner', 'Create a simple Node.js script that prints text to console.', 'Use console.log()', 10),
('Node.js', 'beginner', 'Initialize a Node.js project using npm.', 'Use npm init', 10),
('Node.js', 'beginner', 'Install a package using npm.', 'Use npm install', 10),
('Node.js', 'beginner', 'Import a built-in Node.js module.', 'Use require()', 10),
('Node.js', 'beginner', 'Create a basic HTTP server.', 'Use http module', 10),
('Node.js', 'beginner', 'Send a plain text response from server.', 'Use res.end()', 10),
('Node.js', 'beginner', 'Read a file asynchronously.', 'Use fs.readFile()', 10),
('Node.js', 'beginner', 'Write data to a file.', 'Use fs.writeFile()', 10),
('Node.js', 'beginner', 'Append data to a file.', 'Use fs.appendFile()', 10),
('Node.js', 'beginner', 'Get current directory path.', 'Use __dirname', 10),
('Node.js', 'beginner', 'Get current file path.', 'Use __filename', 10),
('Node.js', 'beginner', 'Use environment variables.', 'Use process.env', 10),
('Node.js', 'beginner', 'Create and use a custom module.', 'Use module.exports', 10),
('Node.js', 'beginner', 'Handle command-line arguments.', 'Use process.argv', 10),
('Node.js', 'beginner', 'Create a simple Express server.', 'Use express()', 10),
('Node.js', 'beginner', 'Create a GET route in Express.', 'Use app.get()', 10),
('Node.js', 'beginner', 'Send JSON response from Express.', 'Use res.json()', 10),
('Node.js', 'beginner', 'Use middleware in Express.', 'Use app.use()', 10),
('Node.js', 'beginner', 'Serve static files using Express.', 'Use express.static()', 10),
('Node.js', 'beginner', 'Handle basic errors in Express.', 'Use error handler', 10);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Node.js', 'intermediate', 'Handle asynchronous code using Promises.', 'Use .then()', 20),
('Node.js', 'intermediate', 'Use async and await syntax.', 'Wrap in async function', 20),
('Node.js', 'intermediate', 'Create RESTful API endpoints.', 'Use HTTP methods', 20),
('Node.js', 'intermediate', 'Parse JSON request body.', 'Use express.json()', 20),
('Node.js', 'intermediate', 'Handle URL parameters.', 'Use req.params', 20),
('Node.js', 'intermediate', 'Handle query parameters.', 'Use req.query', 20),
('Node.js', 'intermediate', 'Implement error-handling middleware.', 'Use four parameters', 20),
('Node.js', 'intermediate', 'Connect Node.js with MongoDB.', 'Use mongoose', 20),
('Node.js', 'intermediate', 'Define a Mongoose schema.', 'Use Schema()', 20),
('Node.js', 'intermediate', 'Perform CRUD operations with MongoDB.', 'Use model methods', 20),
('Node.js', 'intermediate', 'Use dotenv to manage environment variables.', 'Use dotenv package', 20),
('Node.js', 'intermediate', 'Implement request validation.', 'Use validation middleware', 20),
('Node.js', 'intermediate', 'Implement JWT authentication.', 'Use jsonwebtoken', 20),
('Node.js', 'intermediate', 'Hash passwords securely.', 'Use bcrypt', 20),
('Node.js', 'intermediate', 'Implement pagination in API.', 'Use limit and skip', 20),
('Node.js', 'intermediate', 'Implement rate limiting.', 'Use middleware', 20),
('Node.js', 'intermediate', 'Handle file uploads.', 'Use multer', 20),
('Node.js', 'intermediate', 'Implement logging system.', 'Use logging library', 20),
('Node.js', 'intermediate', 'Use CORS in Express.', 'Use cors middleware', 20),
('Node.js', 'intermediate', 'Write unit tests for APIs.', 'Use testing framework', 20);
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Node.js', 'advanced', 'Design a scalable Node.js architecture.', 'Separate layers', 30),
('Node.js', 'advanced', 'Implement role-based access control.', 'Use middleware', 30),
('Node.js', 'advanced', 'Handle API versioning.', 'Use route prefixes', 30),
('Node.js', 'advanced', 'Implement refresh token authentication.', 'Use JWT strategy', 30),
('Node.js', 'advanced', 'Build a real-time chat server.', 'Use WebSockets', 30),
('Node.js', 'advanced', 'Use Socket.IO for real-time events.', 'Use socket events', 30),
('Node.js', 'advanced', 'Implement background jobs.', 'Use job queues', 30),
('Node.js', 'advanced', 'Use Redis for caching.', 'Use Redis client', 30),
('Node.js', 'advanced', 'Optimize API performance.', 'Use caching and async', 30),
('Node.js', 'advanced', 'Implement API security best practices.', 'Sanitize inputs', 30),
('Node.js', 'advanced', 'Handle graceful shutdown.', 'Close server properly', 30),
('Node.js', 'advanced', 'Use clustering for scalability.', 'Use cluster module', 30),
('Node.js', 'advanced', 'Implement event-driven architecture.', 'Use EventEmitter', 30),
('Node.js', 'advanced', 'Create a microservices-based backend.', 'Service separation', 30),
('Node.js', 'advanced', 'Implement API gateway pattern.', 'Central entry point', 30),
('Node.js', 'advanced', 'Implement circuit breaker pattern.', 'Fail fast strategy', 30),
('Node.js', 'advanced', 'Monitor Node.js application.', 'Use monitoring tools', 30),
('Node.js', 'advanced', 'Handle memory leaks in Node.js.', 'Profile heap usage', 30),
('Node.js', 'advanced', 'Deploy Node.js app to production.', 'Use process manager', 30),
('Node.js', 'advanced', 'Design fault-tolerant Node.js system.', 'Use retries and fallbacks', 30);

