-- Java Daily Tasks Questions

-- BEGINNER (20 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Java', 'beginner', 'Write a Java program that prints "Hello, World!" to the console.', 'Use System.out.println()', 10),
('Java', 'beginner', 'Create a variable to store your age and print it.', 'Use int datatype', 10),
('Java', 'beginner', 'Write a program that adds two numbers and displays the result.', 'Use + operator', 10),
('Java', 'beginner', 'Create an array of 5 integers and print each element.', 'Use a for loop', 10),
('Java', 'beginner', 'Write a program using if-else to check if a number is positive or negative.', 'Compare with 0', 10),
('Java', 'beginner', 'Create a simple class with a constructor and one method.', 'Use public class', 10),
('Java', 'beginner', 'Write a for loop that prints numbers from 1 to 10.', 'Use for(int i=1; i<=10; i++)', 10),
('Java', 'beginner', 'Create a String variable and find its length.', 'Use .length() method', 10),
('Java', 'beginner', 'Write a program that converts Celsius to Fahrenheit.', 'Formula: F = (C * 9/5) + 32', 10),
('Java', 'beginner', 'Create a while loop that counts down from 10 to 1.', 'Use while(count > 0)', 10),
('Java', 'beginner', 'Write a method that takes two integers and returns their sum.', 'Use return statement', 10),
('Java', 'beginner', 'Create an object of a class and call its method.', 'Use new keyword', 10),
('Java', 'beginner', 'Write a program to check if a number is even or odd.', 'Use modulo operator %', 10),
('Java', 'beginner', 'Create a simple switch statement for days of the week.', 'Use switch-case', 10),
('Java', 'beginner', 'Write a program that concatenates two strings.', 'Use + or concat()', 10),
('Java', 'beginner', 'Create an ArrayList and add 5 elements to it.', 'Use ArrayList<>', 10),
('Java', 'beginner', 'Write code to read user input using Scanner.', 'Import java.util.Scanner', 10),
('Java', 'beginner', 'Create a program that finds the maximum of three numbers.', 'Use Math.max() or if statements', 10),
('Java', 'beginner', 'Write a do-while loop that runs at least once.', 'Use do { } while()', 10),
('Java', 'beginner', 'Create a method with parameters and call it from main.', 'Define method signature properly', 10);

-- INTERMEDIATE (20 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Java', 'intermediate', 'Implement a class with inheritance using extends.', 'Child class extends Parent class', 20),
('Java', 'intermediate', 'Write a program demonstrating method overloading.', 'Same method name, different parameters', 20),
('Java', 'intermediate', 'Create an interface and implement it in a class.', 'Use implements keyword', 20),
('Java', 'intermediate', 'Write a program using try-catch for exception handling.', 'Catch specific exceptions', 20),
('Java', 'intermediate', 'Implement a program that reads from a file.', 'Use FileReader or BufferedReader', 20),
('Java', 'intermediate', 'Create a HashMap and perform basic operations.', 'Use put(), get(), remove()', 20),
('Java', 'intermediate', 'Write a program using abstract class.', 'Use abstract keyword', 20),
('Java', 'intermediate', 'Implement a simple thread using Runnable interface.', 'Override run() method', 20),
('Java', 'intermediate', 'Create a custom exception class.', 'Extend Exception class', 20),
('Java', 'intermediate', 'Write a program using lambda expressions.', 'Use -> arrow syntax', 20),
('Java', 'intermediate', 'Implement a program using Java Streams API.', 'Use .stream() on collections', 20),
('Java', 'intermediate', 'Create a program demonstrating polymorphism.', 'Parent reference, child object', 20),
('Java', 'intermediate', 'Write a recursive method to calculate factorial.', 'n * factorial(n-1)', 20),
('Java', 'intermediate', 'Implement Comparable interface for sorting objects.', 'Override compareTo()', 20),
('Java', 'intermediate', 'Create a program using Optional to handle null.', 'Use Optional.ofNullable()', 20),
('Java', 'intermediate', 'Write a program demonstrating method overriding.', 'Use @Override annotation', 20),
('Java', 'intermediate', 'Implement a singleton design pattern.', 'Private constructor, static instance', 20),
('Java', 'intermediate', 'Create a program using LinkedList operations.', 'Use addFirst(), addLast()', 20),
('Java', 'intermediate', 'Write a program using enum with methods.', 'Define enum with behavior', 20),
('Java', 'intermediate', 'Implement a binary search algorithm in Java.', 'Divide and conquer approach', 20);

-- ADVANCED (20 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('Java', 'advanced', 'Implement a thread-safe singleton using double-checked locking.', 'Use volatile and synchronized', 30),
('Java', 'advanced', 'Create a custom annotation and use reflection to process it.', 'Use @interface and getDeclaredAnnotations()', 30),
('Java', 'advanced', 'Implement a producer-consumer problem using wait/notify.', 'Use synchronized blocks', 30),
('Java', 'advanced', 'Write a program using CompletableFuture for async operations.', 'Use supplyAsync() and thenApply()', 30),
('Java', 'advanced', 'Implement a custom generic class with bounded type parameters.', 'Use <T extends Comparable<T>>', 30),
('Java', 'advanced', 'Create a connection pool implementation.', 'Manage limited connections', 30),
('Java', 'advanced', 'Write a program using Java NIO for file operations.', 'Use Files and Paths classes', 30),
('Java', 'advanced', 'Implement the Observer design pattern.', 'Subject notifies observers', 30),
('Java', 'advanced', 'Create a custom ClassLoader in Java.', 'Extend ClassLoader and override findClass()', 30),
('Java', 'advanced', 'Write a program demonstrating deadlock and how to prevent it.', 'Lock ordering strategy', 30),
('Java', 'advanced', 'Implement a LRU cache using LinkedHashMap.', 'Override removeEldestEntry()', 30),
('Java', 'advanced', 'Create a program using Executor framework for thread pools.', 'Use Executors.newFixedThreadPool()', 30),
('Java', 'advanced', 'Implement the Factory design pattern.', 'Create objects without exposing logic', 30),
('Java', 'advanced', 'Write a program using Streams parallel processing.', 'Use parallelStream()', 30),
('Java', 'advanced', 'Implement a custom serialization mechanism.', 'Use Externalizable interface', 30),
('Java', 'advanced', 'Create a program using Java Reflection to invoke methods.', 'Use Method.invoke()', 30),
('Java', 'advanced', 'Implement the Builder design pattern with fluent API.', 'Return this for chaining', 30),
('Java', 'advanced', 'Write a program handling concurrent modifications safely.', 'Use ConcurrentHashMap', 30),
('Java', 'advanced', 'Implement a dependency injection framework prototype.', 'Use reflection and annotations', 30),
('Java', 'advanced', 'Create a memory-efficient data structure for large datasets.', 'Consider memory footprint', 30);
-- SQL Daily Tasks Questions

-- BEGINNER (20 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('SQL', 'beginner', 'Write a SELECT statement to retrieve all columns from a table.', 'Use SELECT * FROM tablename', 10),
('SQL', 'beginner', 'Write a query to select specific columns from a table.', 'Use SELECT col1, col2 FROM table', 10),
('SQL', 'beginner', 'Write a WHERE clause to filter rows by a condition.', 'Use WHERE column = value', 10),
('SQL', 'beginner', 'Write a query using ORDER BY to sort results ascending.', 'Use ORDER BY column ASC', 10),
('SQL', 'beginner', 'Write a query to limit the number of rows returned.', 'Use LIMIT n', 10),
('SQL', 'beginner', 'Write an INSERT statement to add a new row.', 'Use INSERT INTO table VALUES (...)', 10),
('SQL', 'beginner', 'Write an UPDATE statement to modify existing data.', 'Use UPDATE table SET col = value', 10),
('SQL', 'beginner', 'Write a DELETE statement to remove rows.', 'Use DELETE FROM table WHERE ...', 10),
('SQL', 'beginner', 'Write a query using AND to combine multiple conditions.', 'Use WHERE cond1 AND cond2', 10),
('SQL', 'beginner', 'Write a query using OR to check alternative conditions.', 'Use WHERE cond1 OR cond2', 10),
('SQL', 'beginner', 'Write a query to find rows where a column IS NULL.', 'Use WHERE column IS NULL', 10),
('SQL', 'beginner', 'Write a query using LIKE for pattern matching.', 'Use % for wildcards', 10),
('SQL', 'beginner', 'Write a query to alias a column with AS.', 'Use SELECT col AS alias', 10),
('SQL', 'beginner', 'Write a query using DISTINCT to get unique values.', 'Use SELECT DISTINCT column', 10),
('SQL', 'beginner', 'Write a query to count the number of rows.', 'Use COUNT(*)', 10),
('SQL', 'beginner', 'Write a query to find the maximum value in a column.', 'Use MAX(column)', 10),
('SQL', 'beginner', 'Write a query to find the minimum value in a column.', 'Use MIN(column)', 10),
('SQL', 'beginner', 'Write a query to calculate the sum of a column.', 'Use SUM(column)', 10),
('SQL', 'beginner', 'Write a query to calculate the average of a column.', 'Use AVG(column)', 10),
('SQL', 'beginner', 'Write a query using IN to check multiple values.', 'Use WHERE col IN (val1, val2)', 10);

-- INTERMEDIATE (20 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('SQL', 'intermediate', 'Write a query with INNER JOIN to combine two tables.', 'Use JOIN ON matching columns', 20),
('SQL', 'intermediate', 'Write a query with LEFT JOIN to include unmatched rows.', 'LEFT JOIN keeps all left table rows', 20),
('SQL', 'intermediate', 'Write a query using GROUP BY to aggregate data.', 'Group by non-aggregated columns', 20),
('SQL', 'intermediate', 'Write a query with HAVING to filter grouped results.', 'HAVING filters after GROUP BY', 20),
('SQL', 'intermediate', 'Write a subquery in the WHERE clause.', 'Use (SELECT ...) as value', 20),
('SQL', 'intermediate', 'Write a query using CASE for conditional logic.', 'Use CASE WHEN THEN ELSE END', 20),
('SQL', 'intermediate', 'Write a query to find the second highest value.', 'Use subquery or OFFSET', 20),
('SQL', 'intermediate', 'Write a UNION query to combine results from two queries.', 'UNION removes duplicates', 20),
('SQL', 'intermediate', 'Write a query using RIGHT JOIN.', 'RIGHT JOIN keeps all right table rows', 20),
('SQL', 'intermediate', 'Write a query to create a table with constraints.', 'Use PRIMARY KEY, NOT NULL', 20),
('SQL', 'intermediate', 'Write a query using COALESCE to handle nulls.', 'COALESCE returns first non-null', 20),
('SQL', 'intermediate', 'Write a query with multiple JOINs across three tables.', 'Chain JOIN statements', 20),
('SQL', 'intermediate', 'Write a query using date functions.', 'Use DATE(), YEAR(), MONTH()', 20),
('SQL', 'intermediate', 'Write a query to add an index to a table.', 'Use CREATE INDEX', 20),
('SQL', 'intermediate', 'Write a correlated subquery.', 'Subquery references outer query', 20),
('SQL', 'intermediate', 'Write a query using EXISTS clause.', 'EXISTS checks if subquery returns rows', 20),
('SQL', 'intermediate', 'Write a query to update data using a JOIN.', 'UPDATE with FROM and JOIN', 20),
('SQL', 'intermediate', 'Write a query using BETWEEN for range conditions.', 'Use BETWEEN val1 AND val2', 20),
('SQL', 'intermediate', 'Write a self-join query.', 'Join table to itself with alias', 20),
('SQL', 'intermediate', 'Write a query to find duplicates in a table.', 'GROUP BY and HAVING COUNT > 1', 20);

-- ADVANCED (20 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('SQL', 'advanced', 'Write a query using window functions with PARTITION BY.', 'Use ROW_NUMBER(), RANK() etc', 30),
('SQL', 'advanced', 'Write a recursive CTE to handle hierarchical data.', 'Use WITH RECURSIVE', 30),
('SQL', 'advanced', 'Write a query to implement pagination efficiently.', 'Use OFFSET with keyset pagination', 30),
('SQL', 'advanced', 'Write a query to pivot rows to columns.', 'Use CASE or PIVOT function', 30),
('SQL', 'advanced', 'Write a query to find running totals.', 'Use SUM() OVER (ORDER BY)', 30),
('SQL', 'advanced', 'Write a query to detect gaps in sequential data.', 'Compare with LAG() or LEAD()', 30),
('SQL', 'advanced', 'Write a query using materialized views.', 'CREATE MATERIALIZED VIEW', 30),
('SQL', 'advanced', 'Write a stored procedure with input parameters.', 'Use CREATE PROCEDURE', 30),
('SQL', 'advanced', 'Write a trigger that fires on INSERT.', 'Use CREATE TRIGGER', 30),
('SQL', 'advanced', 'Write a query to implement upsert (INSERT or UPDATE).', 'Use ON CONFLICT DO UPDATE', 30),
('SQL', 'advanced', 'Write a query using LATERAL JOIN.', 'LATERAL allows correlated subqueries', 30),
('SQL', 'advanced', 'Write a query to calculate moving averages.', 'Use AVG() OVER (ROWS BETWEEN)', 30),
('SQL', 'advanced', 'Write a query for full-text search.', 'Use TSVECTOR and TSQUERY', 30),
('SQL', 'advanced', 'Write a query to handle JSON data.', 'Use JSON functions like ->> or jsonb', 30),
('SQL', 'advanced', 'Write a query to optimize with EXPLAIN ANALYZE.', 'Analyze query execution plan', 30),
('SQL', 'advanced', 'Write a query implementing table partitioning.', 'Use PARTITION BY RANGE', 30),
('SQL', 'advanced', 'Write a query using MERGE statement.', 'MERGE for conditional update/insert', 30),
('SQL', 'advanced', 'Write a function that returns a table.', 'Use RETURNS TABLE', 30),
('SQL', 'advanced', 'Write a query to implement soft deletes.', 'Use deleted_at timestamp column', 30),
('SQL', 'advanced', 'Write a query to handle concurrent updates safely.', 'Use SELECT FOR UPDATE', 30);
-- AI/ML Daily Tasks Questions

-- BEGINNER (20 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('AI/ML', 'beginner', 'Explain the difference between supervised and unsupervised learning.', 'Labeled vs unlabeled data', 10),
('AI/ML', 'beginner', 'Write Python code to load a dataset using pandas.', 'Use pd.read_csv()', 10),
('AI/ML', 'beginner', 'Explain what overfitting means in machine learning.', 'Model memorizes instead of generalizing', 10),
('AI/ML', 'beginner', 'Write code to split data into training and testing sets.', 'Use train_test_split from sklearn', 10),
('AI/ML', 'beginner', 'Explain what a feature and a label are.', 'Feature is input, label is output', 10),
('AI/ML', 'beginner', 'Write code to normalize data using MinMaxScaler.', 'Scale values to 0-1 range', 10),
('AI/ML', 'beginner', 'Explain the concept of training and testing data.', 'Train to learn, test to evaluate', 10),
('AI/ML', 'beginner', 'Write code to create a simple linear regression model.', 'Use LinearRegression from sklearn', 10),
('AI/ML', 'beginner', 'Explain what accuracy means as a metric.', 'Correct predictions / total predictions', 10),
('AI/ML', 'beginner', 'Write code to visualize data using matplotlib.', 'Use plt.scatter() or plt.plot()', 10),
('AI/ML', 'beginner', 'Explain the difference between classification and regression.', 'Categories vs continuous values', 10),
('AI/ML', 'beginner', 'Write code to handle missing values in a dataset.', 'Use fillna() or dropna()', 10),
('AI/ML', 'beginner', 'Explain what a decision tree is.', 'Tree of if-else conditions', 10),
('AI/ML', 'beginner', 'Write code to encode categorical variables.', 'Use LabelEncoder or OneHotEncoder', 10),
('AI/ML', 'beginner', 'Explain what k-NN algorithm does.', 'Classify based on nearest k neighbors', 10),
('AI/ML', 'beginner', 'Write code to calculate correlation between features.', 'Use df.corr()', 10),
('AI/ML', 'beginner', 'Explain what a confusion matrix shows.', 'True/false positives and negatives', 10),
('AI/ML', 'beginner', 'Write code to create a simple neural network layer.', 'Use keras Dense layer', 10),
('AI/ML', 'beginner', 'Explain bias vs variance tradeoff.', 'Underfitting vs overfitting', 10),
('AI/ML', 'beginner', 'Write code to make predictions using a trained model.', 'Use model.predict()', 10);

-- INTERMEDIATE (20 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('AI/ML', 'intermediate', 'Implement cross-validation for model evaluation.', 'Use cross_val_score from sklearn', 20),
('AI/ML', 'intermediate', 'Write code to tune hyperparameters using GridSearchCV.', 'Search over parameter grid', 20),
('AI/ML', 'intermediate', 'Implement a Random Forest classifier.', 'Use RandomForestClassifier', 20),
('AI/ML', 'intermediate', 'Explain and implement regularization (L1/L2).', 'Penalty terms to prevent overfitting', 20),
('AI/ML', 'intermediate', 'Write code for feature selection using correlation.', 'Remove highly correlated features', 20),
('AI/ML', 'intermediate', 'Implement a Support Vector Machine classifier.', 'Use SVC from sklearn', 20),
('AI/ML', 'intermediate', 'Explain and implement PCA for dimensionality reduction.', 'Principal Component Analysis', 20),
('AI/ML', 'intermediate', 'Write code to handle class imbalance.', 'Use SMOTE or class_weight', 20),
('AI/ML', 'intermediate', 'Implement k-means clustering algorithm.', 'Use KMeans from sklearn', 20),
('AI/ML', 'intermediate', 'Explain ROC curve and AUC score.', 'True positive rate vs false positive rate', 20),
('AI/ML', 'intermediate', 'Write code to create an ensemble model.', 'Combine multiple models', 20),
('AI/ML', 'intermediate', 'Implement gradient descent from scratch.', 'Update weights by gradient', 20),
('AI/ML', 'intermediate', 'Explain and implement batch normalization.', 'Normalize layer inputs', 20),
('AI/ML', 'intermediate', 'Write code for text preprocessing in NLP.', 'Tokenize, remove stopwords, stem', 20),
('AI/ML', 'intermediate', 'Implement a multi-layer perceptron.', 'Use MLPClassifier or keras', 20),
('AI/ML', 'intermediate', 'Explain dropout and implement it.', 'Randomly disable neurons during training', 20),
('AI/ML', 'intermediate', 'Write code to save and load a trained model.', 'Use joblib or pickle', 20),
('AI/ML', 'intermediate', 'Implement learning rate scheduling.', 'Decrease LR over epochs', 20),
('AI/ML', 'intermediate', 'Explain precision, recall, and F1 score.', 'Metrics for imbalanced classes', 20),
('AI/ML', 'intermediate', 'Write code for image data augmentation.', 'Rotate, flip, zoom images', 20);

-- ADVANCED (20 questions)
INSERT INTO daily_tasks (technology, difficulty, question, hint, xp_reward) VALUES
('AI/ML', 'advanced', 'Implement a Convolutional Neural Network for image classification.', 'Use Conv2D, MaxPooling2D layers', 30),
('AI/ML', 'advanced', 'Build an LSTM model for sequence prediction.', 'Use LSTM layer for temporal data', 30),
('AI/ML', 'advanced', 'Implement transfer learning using a pretrained model.', 'Use VGG16, ResNet, etc.', 30),
('AI/ML', 'advanced', 'Build a Transformer model for NLP tasks.', 'Use attention mechanism', 30),
('AI/ML', 'advanced', 'Implement a Generative Adversarial Network (GAN).', 'Generator vs Discriminator', 30),
('AI/ML', 'advanced', 'Build a recommendation system using collaborative filtering.', 'User-item interactions', 30),
('AI/ML', 'advanced', 'Implement attention mechanism from scratch.', 'Query, Key, Value matrices', 30),
('AI/ML', 'advanced', 'Build a reinforcement learning agent with Q-learning.', 'Learn policy from rewards', 30),
('AI/ML', 'advanced', 'Implement Word2Vec for word embeddings.', 'Skip-gram or CBOW architecture', 30),
('AI/ML', 'advanced', 'Build a variational autoencoder (VAE).', 'Encoder-decoder with latent space', 30),
('AI/ML', 'advanced', 'Implement BERT fine-tuning for text classification.', 'Use HuggingFace transformers', 30),
('AI/ML', 'advanced', 'Build an object detection model using YOLO.', 'Real-time object detection', 30),
('AI/ML', 'advanced', 'Implement model interpretability with SHAP values.', 'Explain model predictions', 30),
('AI/ML', 'advanced', 'Build a neural machine translation system.', 'Seq2seq with attention', 30),
('AI/ML', 'advanced', 'Implement federated learning concepts.', 'Train on decentralized data', 30),
('AI/ML', 'advanced', 'Build a time series forecasting model with Prophet.', 'Handle seasonality and trends', 30),
('AI/ML', 'advanced', 'Implement model pruning for optimization.', 'Remove unnecessary weights', 30),
('AI/ML', 'advanced', 'Build a speech recognition system.', 'Audio to text conversion', 30),
('AI/ML', 'advanced', 'Implement knowledge distillation.', 'Transfer knowledge from large to small model', 30),
('AI/ML', 'advanced', 'Build an end-to-end ML pipeline with MLflow.', 'Track experiments and deploy', 30);
